#!/bin/bash

. $PROJ_BASE/etc/defs.sh || exit 1

if [[ -n "$PROJ_CURRENT" ]]; then
    echo $PROJ_CURRENT
    exit 0
fi

symlink=$PROJ_BASE/latest
[[ -h $symlink ]] && basename $(readlink $symlink)
exit 0
