#!/bin/bash

. $PROJ_BASE/etc/defs.sh || exit 1

projects=( $($PROJ_BASE/sbin/get_all) ) || die "could not list projects"
current=$($PROJ_BASE/sbin/get_current) || die "could not get current project"
[[ "${#projects[@]}" -gt 0 ]] || die "no projects have been configured"

echo
for project in "${projects[@]}"; do
    printf "  "
    if [[ "$project" == "$current" ]]; then
        printf "\x1B[92m%s\x1B[0m" $project
    else
        printf "%s" $project
    fi
    home_symlink=$PROJ_BASE/all/$project/home
    if [[ -h $home_symlink ]]; then
        printf " → %s" $(readlink $home_symlink)
    fi
    printf "\n"
done
echo ""
